version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - '8761:8761'
    networks:
      mynetwork:

networks:
  mynetwork:
    external: true